### PR TITLE
bump(api-client-core): v0.13.7

### PR DESCRIPTION
**Pull request by MikePresman**
This release is for the changes made here: https://github.com/gadget-inc/js-clients/commit/3144ce116eda1a5d6676a599fbc6605c907c48a6

## PR Checklist

- [ ] Important or complicated code is tested
- [ ] Any user facing changes are documented in the Gadget-side changelog
- [ ] Any immediate changes are slated for release in Gadget via a generated package dependency bump
- [ ] Versions within this monorepo are matching and there's a valid upgrade path

### CODE REVIEW

**Comment by jasong689** [comment]
Can we hold off bumping the version for a day or so? I'd like to get this https://github.com/gadget-inc/gadget/pull/6569 merged since there's a bug with `d.ts` generation with `0.13.6` Gadget side right now. We could also merge this but skip updating dependencies Gadget side until that PR is merged. I'm cool with either option

**Comment by jcao49** [comment]
> Can we hold off bumping the version for a day or so? I'd like to get this [gadget-inc/gadget#6569](https://github.com/gadget-inc/gadget/pull/6569) merged since there's a bug with `d.ts` generation with `0.13.6` Gadget side right now. We could also merge this but skip updating dependencies Gadget side until that PR is merged. I'm cool with either option

👋 noticed we're all trying to bump `api-client-core`, I have a pr [here](https://github.com/gadget-inc/js-clients/pull/185) also trying to bump the version. Should I wait for you guys to merge your version bumps first ? @jasong689 @MikePresman

**Comment by angelini** [comment]
@MikePresman makes sense to wait for everyone and do one bigger upgrade. Let's use that time to fix the `regenerate-js-clients` task in Gadget

**Comment by jasong689** [comment]
Gadget PR has been merged. @MikePresman do you want to coordinate with @jcao49 to get both your changes out in `0.13.7`?

**Pull request merged**
