### PR TITLE
add a table of contents to the react package readme file

### PR DESCRIPTION
**Pull request by rdraward**
The README for `@gadgetinc/react` has become pretty big. A table of contents will be useful for finding the docs I want to look at

## PR Checklist

- [ ] Important or complicated code is tested
- [ ] Any user facing changes are documented in the Gadget-side changelog
- [ ] Any immediate changes are slated for release in Gadget via a generated package dependency bump
- [ ] Versions within this monorepo are matching and there's a valid upgrade path

### CODE REVIEW

**Comment by airhorns** [comment]
Is this materially better than the autogenerated table of contents right next to it on the right? I kinda feel like this just duplicates that

**Comment by rdraward** [comment]
> Is this materially better than the autogenerated table of contents right next to it on the right? I kinda feel like this just duplicates that

I only get the auto-gen table of contents when I'm actually looking at the README file. Do you see something different @airhorns? I agree, I'd would rather not duplicate but unless the README is at the actual repo root level I don't seem to get a working toc

https://github.com/gadget-inc/js-clients/assets/20960033/d6697f7b-64a9-4990-a81f-004d41b96a0c

**Comment by airhorns** [comment]
Oh dang sorry I was not paying close attention -- this is in the js-clients repo! I think this TOC totally makes sense over here, but, what do you think about deduplicating this content and adding a link to docs.gadget.dev from within the readme so we don't need to maintain both?

**Comment by rdraward** [comment]
I hadn't seen the docs in our new ref section! Totally agree, a link is a much better way to reduce the maintenance burden. We don't need this info in two places

**Comment by rdraward** [comment]
> @rdraward want to ship a link?

Sorry, I'll close this PR! We can totally replace the existing content with a link to our Ref docs

**Pull request closed without merging**
