### PR TITLE
Support weird shopify extensions context

### PR DESCRIPTION
**Pull request by airhorns**
Shopify's new extension functionality supports importing and running JS modules that make external API calls, in both checkout extensions and the new admin extensions. Gadget's client currently throws for two reasons when you try this though:
 - Shopify's locked down extension environment (powered by [shopify/remote-ui](https://github.com/Shopify/remote-ui)) has a `globalThis.fetch`, but doesn't have a `globalThis.WebSocket`, which we expect to be present. It's absence is ok though -- extensions don't really need to open up transactions against Gadget and so don't need websockets. In a subscriptions/livequery-y future that'd change, but investing in a whole other transport is a lot of work. We can make normal reads and writes from an extension work just fine though by not requiring websockets to be present until you go to use a feature which actually needs them
 - Our deep equal library is old and includes a LOT of polyfills, one of which breaks for really weird arcane reasons I couldn't quite figure out. I don't think it really matters though -- there's a bunch of newer ones that dont support IE8 (which we already definitely don't) and are much smaller and faster. I switched to the fastest one I could find that also works good in a react context where we use it. Gives a **25%** bundle size reduction for the simple react read test bundle, after gzip (!!)
 
 Bundle size before:
 
```
vite v4.4.7 building for production...
✓ 173 modules transformed.
dist/api-read-stats.html           210.92 kB │ gzip: 46.91 kB
dist/browser-ponyfill-a950d05c.js   12.53 kB │ gzip:  3.50 kB
dist/test-bundle-api-read.js       199.92 kB │ gzip: 34.47 kB
dist/api-read-stats.html            211.51 kB │ gzip: 46.98 kB
dist/browser-ponyfill-0b1c63f2.cjs    8.88 kB │ gzip:  3.07 kB
dist/test-bundle-api-read.cjs       130.16 kB │ gzip: 28.08 kB
✓ built in 800ms
vite v4.4.7 building for production...
✓ 449 modules transformed.
dist/react-read-stats.html         302.31 kB │ gzip: 56.84 kB
dist/test-bundle-react-read.js       0.09 kB │ gzip:  0.10 kB
dist/browser-ponyfill-02a74330.js   12.44 kB │ gzip:  3.50 kB
dist/react-read-335fd62e.js        305.32 kB │ gzip: 63.71 kB
dist/react-read-stats.html          306.31 kB │ gzip: 56.96 kB
dist/test-bundle-react-read.cjs       0.17 kB │ gzip:  0.16 kB
dist/browser-ponyfill-f7274c25.cjs    8.83 kB │ gzip:  3.08 kB
dist/react-read-a635b001.cjs        205.06 kB │ gzip: 53.23 kB
✓ built in 1.21s
vite v4.4.7 building for production...
✓ 983 modules transformed.
dist/shopify-read-stats.html       514.75 kB │ gzip:  77.59 kB
dist/test-bundle-shopify-read.js     0.12 kB │ gzip:   0.12 kB
dist/browser-ponyfill-0d130bc8.js   12.45 kB │ gzip:   3.50 kB
dist/shopify-read-7f8278c4.js      624.64 kB │ gzip: 122.39 kB
dist/shopify-read-stats.html        515.26 kB │ gzip:  77.60 kB
dist/test-bundle-shopify-read.cjs     0.19 kB │ gzip:   0.17 kB
dist/browser-ponyfill-78d0ca92.cjs    8.83 kB │ gzip:   3.08 kB
dist/shopify-read-2349a160.cjs      439.10 kB │ gzip: 104.25 kB
✓ built in 2.34s
```

 Bundle size after:
 
 ```
 ✓ 173 modules transformed.
dist/api-read-stats.html           210.92 kB │ gzip: 46.91 kB
dist/browser-ponyfill-a950d05c.js   12.53 kB │ gzip:  3.50 kB
dist/test-bundle-api-read.js       200.34 kB │ gzip: 34.58 kB
dist/api-read-stats.html            211.51 kB │ gzip: 46.98 kB
dist/browser-ponyfill-0b1c63f2.cjs    8.88 kB │ gzip:  3.07 kB
dist/test-bundle-api-read.cjs       130.55 kB │ gzip: 28.17 kB
✓ built in 806ms
vite v4.4.7 building for production...
✓ 334 modules transformed.
dist/react-read-stats.html         265.78 kB │ gzip: 52.04 kB
dist/test-bundle-react-read.js       0.09 kB │ gzip:  0.10 kB
dist/browser-ponyfill-98d7d84f.js   12.44 kB │ gzip:  3.50 kB
dist/react-read-27a226a5.js        251.62 kB │ gzip: 49.47 kB
dist/react-read-stats.html          267.69 kB │ gzip: 52.06 kB
dist/test-bundle-react-read.cjs       0.17 kB │ gzip:  0.16 kB
dist/browser-ponyfill-fee63aab.cjs    8.83 kB │ gzip:  3.08 kB
dist/react-read-e88a8a02.cjs        164.79 kB │ gzip: 40.48 kB
✓ built in 1.01s
vite v4.4.7 building for production...
✓ 868 modules transformed.
dist/shopify-read-stats.html       477.30 kB │ gzip:  73.18 kB
dist/test-bundle-shopify-read.js     0.12 kB │ gzip:   0.12 kB
dist/browser-ponyfill-e69908c2.js   12.45 kB │ gzip:   3.50 kB
dist/shopify-read-1a415721.js      570.97 kB │ gzip: 107.91 kB
dist/shopify-read-stats.html        477.75 kB │ gzip: 73.18 kB
dist/test-bundle-shopify-read.cjs     0.19 kB │ gzip:  0.17 kB
dist/browser-ponyfill-6324cc0a.cjs    8.83 kB │ gzip:  3.08 kB
dist/shopify-read-7b5ce7af.cjs      398.85 kB │ gzip: 91.40 kB
✓ built in 2.15s
```

### CODE REVIEW

**Comment by thegedge** [comment]
> I switched to the fastest one I could find that also works good in a react context where we use it

Looks like this win is missing from this PR, at the moment!

**Comment by airhorns** [comment]
> Looks like this win is missing from this PR, at the moment!
Forgot to push my bad!

**Review by infiton — APPROVED** [review]
lgtm

**Review by thegedge — APPROVED** [review]
🚀

**Pull request merged**
